import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split('''
CMSIS/Device/ST/STM32F4xx/Source/Templates/system_stm32f4xx.c
STM32F4xx_StdPeriph_Driver/Src/misc.c
STM32F4xx_StdPeriph_Driver/Src/stm32f4xx_dma.c
STM32F4xx_StdPeriph_Driver/Src/stm32f4xx_dma2d.c
STM32F4xx_StdPeriph_Driver/Src/stm32f4xx_gpio.c
STM32F4xx_StdPeriph_Driver/Src/stm32f4xx_i2c.c
STM32F4xx_StdPeriph_Driver/Src/stm32f4xx_ltdc.c
STM32F4xx_StdPeriph_Driver/Src/stm32f4xx_rcc.c
STM32F4xx_StdPeriph_Driver/Src/stm32f4xx_spi.c
STM32F4xx_StdPeriph_Driver/Src/stm32f4xx_usart.c
STM32F4xx_StdPeriph_Driver/Src/stm32f4xx_exti.c
STM32F4xx_StdPeriph_Driver/Src/stm32f4xx_syscfg.c
STM32F4xx_StdPeriph_Driver/Src/stm32f4xx_fmc.c
''')

#add for startup script
if rtconfig.CROSS_TOOL == 'gcc':
     src = src + ['CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/startup_stm32f429_439xx.s']
elif rtconfig.CROSS_TOOL == 'keil':
     src = src + ['CMSIS/Device/ST/STM32F4xx/Source/Templates/arm/startup_stm32f429_439xx.s']
elif rtconfig.CROSS_TOOL == 'iar':
    src = src + ['CMSIS/Device/ST/STM32F4xx/Source/Templates/iar/startup_stm32f429_439xx.s']
#add add head file path in the KEIL project
path = [cwd + '/STM32F4xx_StdPeriph_Driver/Inc',
    cwd + '/CMSIS/Device/ST/STM32F4xx/Include',
    cwd + '/CMSIS/Include']
#add defien in the project settings :C/C++
CPPDEFINES = ['USE_STDPERIPH_DRIVER','STM32F429_439xx']
#add project group
group = DefineGroup('STM32F429_Periph_Lib', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
